import { initializeApp } from "firebase/app";
import { initializeFirestore, collection, doc, getDocs, getDoc, setDoc, deleteDoc, updateDoc } from "firebase/firestore";
import firebaseConfig from "../../firebase-applet-config.json";

// Initialize Firebase using the configuration file generated by the environment
const app = initializeApp(firebaseConfig);

// Initialize Firestore with the database ID specified in the configuration and force long polling
export const db = initializeFirestore(app, {
  experimentalForceLongPolling: true,
}, firebaseConfig.firestoreDatabaseId);

export { collection, doc, getDocs, getDoc, setDoc, deleteDoc, updateDoc };
